[package]
name = "gutted-client"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "gutted-client"
path = "src/main.rs"

[dependencies]
tokio.workspace = true
quinn.workspace = true
rustls.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
bytes.workspace = true
hex.workspace = true
sha2.workspace = true
gutted-proto = { path = "../gutted-proto" }
wgpu       = "0.20"
winit      = "0.30"
pollster   = "0.3"
bytemuck   = { version = "1", features = ["derive"] }
font8x8    = { version = "0.3", default-features = false, features = ["unicode"] }
