[package]
name = "gutted-host"
version.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"

[[bin]]
name = "gutted-host"
path = "src/main.rs"

[build-dependencies]
cc = "1"
pkg-config = "0.3"

[dependencies]
tokio.workspace = true
quinn.workspace = true
rustls.workspace = true
rcgen.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
bytes.workspace = true
sha2.workspace = true
hex.workspace = true
tokio-tungstenite = "0.24"
futures-util = "0.3"
gutted-proto = { path = "../gutted-proto" }
